<?php
$value = null;
if (isset($query['id'])) {
    $value = $query['id'];
    if (is_array($value)) {
        $value = implode(',', $value);
    }
}
?>
<div class="field row">
    <div class="field-meta col-3">
        <label class="form-label" for="id"><?php echo $this->translate('Search by ID'); ?></label>
        <button type="button" data-bs-toggle="collapse" data-bs-target="#id-help" class="btn btn-outline-info btn-sm border-0"><i class="bi bi-info-circle"></i></button>
        <div class="collapsible collapse text-secondary" id="id-help">
            <div class="field-description"><?php echo $this->translate('Searches for resources by Omeka S ID. You can search for more than one ID by separating them by commas.'); ?></div>
        </div>
    </div>
    <div class="inputs col-9">
        <input class="form-control" type="text" name="id" id="id" value="<?php echo $this->escapeHtml($value); ?>">
    </div>
</div>
