<?php
$value = isset($query['media_type']) ? $query['media_type'] : null;
?>
<div class="field row">
    <div class="field-meta col-3">
        <label for="fulltext_search"><?php echo $this->translate('Search by MIME type'); ?></label>
    </div>
    <div class="inputs col-9">
        <input type="text" name="media_type" id="media_type" value="<?php echo $this->escapeHtml($value); ?>">
    </div>
</div>
