<?php
$translate = $this->plugin('translate');
// Prepare the resource class query.
$ids = isset($query['resource_class_id']) ? $query['resource_class_id'] : [];
if (!is_array($ids)) {
    $ids = [$ids];
}
$ids = array_filter($ids);
if (!$ids) {
    $ids = [null];
}
$optionsQuery = [];
if ($this->status()->isSiteRequest()) {
    if ($this->siteSetting('vocabulary_scope') === 'sitewide') {
        $optionsQuery['site_id'] = $this->layout()->site->id();
    } elseif ($this->siteSetting('vocabulary_scope') === 'cross-site') {
        $optionsQuery['used'] = true;
    }
}

?>
<div id="resource-class" class="field removable multi-value row" role="group">
    <div class="field-meta col-3 position-relative">
        <span id="by-resource-class-label" class="label form-label"><?php echo $translate('Search by class'); ?></span>
        <button type="button" data-bs-toggle="collapse" data-bs-target="#resource-class-help" class="btn btn-outline-info btn-sm border-0"><i class="bi bi-info-circle"></i></button>
        <div class="collapsible collapse text-secondary" id="resource-class-help">
            <div class="field-description"><?php echo $translate('Searches for resources that are any of these classes.'); ?></div>
        </div>
        <button type="button" class="add-value o-icon-add button btn position-absolute top-0 end-0" aria-label="<?php echo $translate('Add new class'); ?>" title="<?php echo $translate('Add new class'); ?>"><i class="bi bi-plus-square"></i></button>
    </div>
    <div class="inputs col-9">
        <?php foreach ($ids as $id): ?>
        <div class="value">
            <?php echo $this->resourceClassSelect([
                'name' => 'resource_class_id[]',
                'attributes' => [
                    'value' => $id,
                    'aria-labelledby' =>  'by-resource-class-label',
                    'class' => 'form-select',
                ],
                'options' => [
                    'query' => $optionsQuery
                ]
            ]); ?>
            <button type="button" class="o-icon-delete remove-value button btn" aria-label="<?php echo $translate('Remove value'); ?>" title="<?php echo $translate('Remove value'); ?>"><i class="bi bi-x-square"></i></button>
        </div>
        <?php endforeach; ?>
    </div>
</div>
