<?php
use Laminas\Form\Element;

$sortConfigContext = $this->status()->isAdminRequest() ? 'admin' : 'public';
switch ($resourceType) {
    case 'itemSet':
        $sortConfigResourceType = 'item_sets';
        break;
    case 'media':
        $sortConfigResourceType = 'media';
        break;
    case 'item':
    default:
        $sortConfigResourceType = 'items';
}
$sortConfig = $this->browse()->getBrowseService()->getSortConfig($sortConfigContext, $sortConfigResourceType);

$sortBy = new Element\Select('sort_by');
$sortBy->setAttribute('aria-label', $this->translate('Sort by'));
$sortBy->setAttribute('class', 'form-select');
$sortBy->setEmptyOption($this->translate('Select sort by…'));
$sortBy->setValueOptions($sortConfig);
$sortBy->setValue($query['sort_by'] ?? '');

$sortOrder = new Element\Select('sort_order');
$sortOrder->setAttribute('aria-label', $this->translate('Sort order'));
$sortOrder->setAttribute('class', 'form-select');
$sortOrder->setEmptyOption($this->translate('Select sort order…'));
$sortOrder->setValueOptions([
    'asc' => $this->translate('Ascending'),
    'desc' => $this->translate('Descending'),
]);
$sortOrder->setValue($query['sort_order'] ?? '');
?>
<div class="field row">
    <div class="field-meta col-3">
        <label class="form-label"><?php echo $this->translate('Sort'); ?></label>
    </div>
    <div class="inputs col-9">
        <?php echo $this->formSelect($sortBy); ?>
        <?php echo $this->formSelect($sortOrder); ?>
    </div>
</div>
