<?php
$translate = $this->plugin('translate');
?>
<nav class="pagination d-flex align-items-baseline" role="navigation">
<?php if ($totalCount): ?>
    <form method="GET" action="" class="d-flex align-items-center">
        <?php echo $this->queryToHiddenInputs(['page']); ?>
        <div class="inline-block me-2">
            <input type="text" name="page" class="page-input-top form-control" value="<?php echo $currentPage; ?>" size="4" <?php echo ($pageCount == 1) ? 'readonly' : ''; ?> aria-label="<?php echo $translate('Page'); ?>">
        </div>
        <div class="inline-block">
            <span class="page-count"><?php echo sprintf($translate('of %s'), $pageCount); ?></span>
        </div>
    </form>

    <?php if ($currentPage != 1): ?>
    <?php echo $this->hyperlink($translate('Previous'), $previousPageUrl, ['class' => 'previous o-icon-prev button px-2', 'title' => $translate('Previous'), 'aria-label' => $translate('Previous')]); ?>
    <?php else: ?>
    <span class="previous o-icon-prev button inactive"></span>
    <?php endif; ?>

    <?php if ($currentPage < $pageCount): ?>
    <?php echo $this->hyperlink($translate('Next'), $nextPageUrl, ['class' => 'next o-icon-next button px-2', 'title' => $translate('Next'), 'aria-label' => $translate('Next')]); ?>
    <?php else: ?>
    <span class="next o-icon-next button inactive"></span>
    <?php endif; ?>

    <?php
    $from = $offset + 1;
    $to = ($currentPage < $pageCount) ? $offset + $perPage : $totalCount;
    ?>
    <span class="row-count px-2"><?php echo sprintf($translate('%1$s–%2$s of %3$s'), $from, $to, $totalCount); ?></span>
<?php else: ?>
    <?php echo $translate('0 results'); ?>
<?php endif; ?>
</nav>
