<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$thumbnail = $this->plugin('thumbnail');

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;

$this->htmlElement('body')->appendAttribute('class', 'item-set resource browse');
?>

<?php echo $this->pageTitle($translate('Item sets'), 2); ?>

<?php echo $this->searchFilters(); ?>

<div class="browse-controls row my-4">
    <div class="col-4"><?php echo $this->pagination(); ?></div>
    <div class="col-4"><?php echo $this->hyperlink($translate('Advanced search'), $this->url(null, ['action' => 'search'], true), ['class' => 'advanced-search']); ?></div>
</div>

<?php $this->trigger('view.browse.before'); ?>
<div class="resource-list row">
<?php
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');
foreach ($itemSets as $itemSet):
    $heading = $headingTerm ? $itemSet->value($headingTerm, ['default' => $translate('[Untitled]'), 'lang' => $valueLang]) : $itemSet->displayTitle(null, $valueLang);
    $body = $bodyTerm ? $itemSet->value($bodyTerm, ['lang' => $valueLang]) : $itemSet->displayDescription(null, $valueLang);
?>
    <div class="item-set resource col-sm-6 col-md-3 col-lg-2">
        <div class="card h-100">
            <?php
            echo $thumbnail($itemSet, 'medium', ['class' => 'card-img-top']);
            ?>
            <div class="card-body d-flex flex-column">
                <div class="mt-auto">
                    <?php
                    $linkContent = sprintf('<span class="resource-name">%s</span>', $escape($heading));
                    echo $itemSet->linkRaw($linkContent, null, ['class' => 'resource-link stretched-link']);
                    ?>
                    <?php if ($body): ?>
                    <div class="description"><?php echo $escape($body); ?></div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
<?php endforeach; ?>
</div>
<?php $this->trigger('view.browse.after'); ?>
<div class="browse-controls row my-4">
    <div class="col-4"><?php echo $this->pagination(); ?></div>
</div>
