<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$thumbnail = $this->plugin('thumbnail');
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;

$query = $this->params()->fromQuery();
$itemSetShow = isset($itemSet);
if ($itemSetShow):
    $this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));
    $this->htmlElement('body')->appendAttribute('class', 'item-set');
    $query['item_set_id'] = $itemSet->id();
endif;
?>

<?php if ($itemSetShow): ?>
    <?php echo $this->pageTitle($itemSet->displayTitle(null, $valueLang), 2); ?>
    <h3><?php echo $translate('Item set'); ?></h3>
    <div class="metadata">
        <?php echo $this->resourcePageBlocks($itemSet)->getBlocks(); ?>
    </div>
    <div class="item-set-items">
    <?php echo '<h3>' . $escape($translate('Items')) . '</h3>'; ?>
<?php else: ?>
    <?php echo $this->pageTitle($translate('Items'), 2); ?>
<?php endif; ?>

<?php echo $this->searchFilters(); ?>

<div class="browse-controls row my-4">
    <div class="col-5"><?php echo $this->pagination(); ?></div>
    <div class="col-2 d-flex align-items-center"><?php echo $this->hyperlink($translate('Advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $query], true), ['class' => 'advanced-search']); ?></div>
    <div class="col-5"><?php echo $this->browse()->renderSortSelector('items'); ?></div>
</div>

<?php $this->trigger('view.browse.before'); ?>
<div class="resource-list row gx-3 gy-5 justify-content-center">
<?php
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');
foreach ($items as $item):
    $heading = $headingTerm ? $item->value($headingTerm, ['default' => $translate('[Untitled]'), 'lang' => $valueLang]) : $item->displayTitle(null, $valueLang);
    $body = $bodyTerm ? $item->value($bodyTerm, ['lang' => $valueLang]) : $item->displayDescription(null, $valueLang);
?>
    <div class="item resource col-sm-6 col-md-3 col-lg-2">
      <div class="h-100 d-flex flex-column">

        <?php
        echo $thumbnail($item, 'medium', ['class' => 'card-img-top']);
        ?>
        <div class="mt-auto">
            <?php
            $linkContent = sprintf('<span class="resource-name">%s</span>', $escape($heading));
            echo $item->linkRaw($linkContent, null, ['class' => 'resource-link stretched-link']);
            ?>
            <?php if ($body): ?>
              <div class="description"><?php echo $escape($body); ?></div>
            <?php endif; ?>
        </div>
      </div>
    </div>
<?php endforeach; ?>
</div>
<?php echo ($itemSetShow) ? '</div>' : ''; ?>
<?php $this->trigger('view.browse.after'); ?>
<div class="my-4"><?php echo $this->pagination(); ?></div>
