<?php if ($singleSelect): ?>
<?php echo $this->formElement($singleSelect); ?>
<?php else: ?>
<ul class="list-group">
    <?php foreach ($itemSets as $itemSet): ?>
    <li class="list-group-item">
        <label>
            <input
                class="item-set form-check-input"
                type="<?php echo ('multiple_list' === $facet->data('select_type')) ? 'checkbox' : 'radio'; ?>"
                name="<?php echo sprintf('item_set_%s', $facet->id()); ?>"
                data-item-set-id="<?php echo $this->escapeHtml($itemSet->id()); ?>">
                <?php echo $itemSet->title(); ?>
        </label>
    </li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
