<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$thumbnail = $this->plugin('thumbnail');
$hyperlink = $this->plugin('hyperlink');
?>
<div class="preview-block my-5">

<?php if ($this->heading): ?>
<div class="d-flex mx-4 mb-4">
  <h2 class="flex-grow-1"><?php echo $escape($this->heading); ?></h2>
  <?php if ($this->linkText): ?>
  <div>
    <?php
    $browse_link_text = $escape($this->linkText) . ' <i class="bi bi-arrow-right"></i>';
    echo $hyperlink->raw($browse_link_text, $this->url(
        'site/resource', ['controller' => $this->resourceType, 'action' => 'browse'], ['query' => $this->query], true
    )); ?>
  </div>
  <?php endif; ?>
</div>
<?php endif; ?>

<div class="resource-list preview row g-3">
    <?php
    $showThumbnail = in_array('thumbnail', $this->components);
    $showHeading = in_array('resource-heading', $this->components);
    $showBody = in_array('resource-body', $this->components);
    $headingTerm = $this->siteSetting('browse_heading_property_term');
    $bodyTerm = $this->siteSetting('browse_body_property_term');

    $filterLocale = (bool) $this->siteSetting('filter_locale_values');
    $lang = $this->lang();
    $valueLang = $filterLocale ? [$lang, ''] : null;

    foreach ($this->resources as $resource):
        $heading = $headingTerm ? $resource->value($headingTerm, ['default' => $translate('[Untitled]'), 'lang' => $valueLang]) : $resource->displayTitle(null, $valueLang);
        $body = $bodyTerm ? $resource->value($bodyTerm, ['lang' => $valueLang]) : $resource->displayDescription(null, $valueLang);
    ?>
        <div class="<?php echo $this->resourceType; ?> resource col-sm-6 col-md-3 col-lg-2">
          <div class="h-100 d-flex flex-column position-relative">
            <?php
            if ($showThumbnail): ?>
                <div><?php echo $this->thumbnail($resource, 'medium', ['class' => 'img-fluid']); ?></div>
            <?php endif; ?>
            <div class="mt-auto">
                <?php
                $linkContent = '';
                if ($showHeading):
                    $linkContent .= '<span class="resource-name">' . $escape($heading) . '</span>';
                endif;
                if ($linkContent !== '') {
                    echo $resource->linkRaw($linkContent, null, ['class' => 'resource-link stretched-link']);
                }
                ?>
                <?php if ($showBody && $body): ?>
                <div class="description"><?php echo $escape($body); ?></div>
                <?php endif; ?>
            </div>
          </div>
        </div>
    <?php endforeach; ?>
</div>

</div>
