<div class="py-3">
    <div>
        <p class="text-center fs-4 py-3">Granthappura in Numbers</p>

        <div class="d-none d-md-block">
            <div class="counts row justify-content-center">
                <div class="col-1 mx-4">
                    <p class="theNum fs-2 fw-bold" id="NumOne"><?php echo $items; ?></p>

                    <p class="theCap">Items</p>
                </div>

                <div class="col-1 border-start mx-4">
                    <p class="theNum fs-2 fw-bold" id="NumTwo"><?php echo $languages; ?></p>

                    <p class="theCap">Languages</p>
                </div>

                <div class="col-1 border-start mx-4">
                    <p class="theNum fs-2 fw-bold" id="NumThree"><?php echo $collections; ?></p>

                    <p class="theCap">Collections</p>
                </div>

                <div class="col-1 border-start mx-4">
                    <p class="theNum fs-2 fw-bold" id="NumFour"><?php echo $authors; ?></p>

                    <p class="theCap">Authors</p>
                </div>

                <div class="col-1 border-start mx-4">
                    <p class="theNum fs-2 fw-bold" id="NumFive"><?php echo $pages; ?></p>

                    <p class="theCap">Pages</p>
                </div>
            </div>
        </div>

        <div class="d-md-none">
            <div class="counts row justify-content-center text-center">
                <div class="col-3 mx-4">
                    <p class="theNum fs-5 fw-bold" id="NumOne"><?php echo $items; ?></p>

                    <p class="theCap">Items</p>
                </div>

                <div class="col-3 mx-4">
                    <p class="theNum fs-5 fw-bold" id="NumTwo"><?php echo $languages; ?></p>

                    <p class="theCap">Languages</p>
                </div>

                <div class="col-3 mx-4">
                    <p class="theNum fs-5 fw-bold" id="NumThree"><?php echo $collections; ?></p>

                    <p class="theCap">Collections</p>
                </div>

                <div class="col-3 mx-4">
                    <p class="theNum fs-5 fw-bold" id="NumFour"><?php echo $authors; ?></p>

                    <p class="theCap">Authors</p>
                </div>

                <div class="col-3 mx-4">
                    <p class="theNum fs-5 fw-bold" id="NumFive"><?php echo $pages; ?></p>

                    <p class="theCap">Pages</p>
                </div>
            </div>
        </div>
    </div>
</div>