<?php
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');
?>
<div class="resource-list row gx-3 gy-5">
    <?php foreach ($items as $item): ?>
    <?php
    $heading = $headingTerm ? $item->value($headingTerm, ['default' => $this->translate('[Untitled]')]) : $item->displayTitle();
    $body = $bodyTerm ? $item->value($bodyTerm) : $item->displayDescription();
    ?>
    <div class="item resource col-6 col-md-3">
        <?php echo $item->linkPretty('square', $heading); ?>
        <?php if ($body): ?>
        <div class="description"><?php echo $this->escapeHtml($body); ?></div>
        <?php endif; ?>
    </div>
    <?php endforeach; ?>
</div>
