<?php
$resourceMedia = $resource->media();
$translate = $this->plugin('translate');

$pdf_link = NULL;
$has_flipbook = FALSE;
$media_link = NULL;

foreach ($resourceMedia as $media) {
    /** @var \Omeka\Api\Representation\MediaRepresentation $media */
    $ingestor = $media->ingester();
    if ($ingestor == 'url') {
        $url = $media->source();
        if (preg_match('/.pdf$/', $url)) {
            // Not to show this media item of PDF linked with image if this item has flipbook.
            $pdf_link = '<div class="mb-4"><a class="btn btn-primary" href="' . $url . '" target="_blank">' . $translate('Download PDF') . ' <i class="bi bi-download"></i></a></div>';
        }
    }
    elseif ($ingestor == 'html') {
        $data = $media->mediaData();
        if (!empty($data['html']) && preg_match('/\<iframe /', $data['html'])) {
            $has_flipbook = TRUE;
        }
    }
    else if ($ingestor == 'tify_iiif_presentation') {
        $has_flipbook = TRUE;
    }
    else if ($ingestor == 'link') {
        $media_link = $media->render([
            'attributes' => ['class' => 'btn btn-primary', 'target' => '_blank'],
            'suffix' => ' <i class="bi bi-download"></i>',
        ]);
    }

}

?>
<?php if ($resourceMedia): ?>
<div class="media-embeds row gx-3 gy-5 align-items-center mb-5">
    <?php foreach ($resourceMedia as $media): ?>
        <?php
        $ingestor = $media->ingester();
        if ($ingestor == 'url') {
            $url = $media->source();
            if (preg_match('/.pdf$/', $url) && ($has_flipbook | !empty($media_link))) {
                // Not to show this media of stored PDF linked with image if this item has a flipbook.
                continue;
            }
        }
        else if ($ingestor == 'link' ) {
            if (!$has_flipbook) {
                echo $media_link;
            }
            else {
                continue;
            }
        }
        ?>
        <div class="col-12 text-center">
            <?php
            if (!empty($media_link)) {
                echo $media_link;
            }
            elseif (!empty($pdf_link)) {
                echo $pdf_link;
            }
            ?>
            <?php
            if ($ingestor == 'tify_iiif_presentation') {
                $item = $this->resource;
                echo $media->render(['alternate_url' => '//gpura.local/iiif-presentation/3/item/' . $item->id() . '/manifest']);
            }
            else {
                echo $media->render();
            }
            ?>
        </div>
        <?php endforeach; ?>
</div>
<?php endif; ?>
