<?php
$translate = $this->plugin('translate');
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
// $this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Source+Code+Pro|Lato:400,400italic,700,700italic');
// $this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->appendStylesheet($this->assetUrl('bootstrap/css/bootstrap-gpura.min.css'));
$this->headLink()->appendStylesheet("https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css");
// $this->headLink()->appendStylesheet($this->assetUrl('css/style.css', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('bootstrap/js/bootstrap.min.js'));
// $this->headScript()->appendFile($this->assetUrl('js/global.js', 'Omeka'));
$this->trigger('view.layout');
$userBar = $this->userBar();

$site_title = $site->title();
$org_title = $this->themeSetting('org_title');
$org_logo = $this->themeSettingAssetUrl('org_logo');
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html')->setAttribute('lang', $this->lang()); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <?php echo $this->htmlElement('body'); ?>
        <?php echo $userBar; ?>

        <nav class="navbar navbar-expand-lg p-0 border-bottom shadow-sm">
          <div class="container-fluid d-flex flex-row">
              <a class="navbar-brand pe-3 me-0 border-end" href="/">
                <img class="" src="<?php echo $this->themeSettingAssetUrl('logo'); ?>"  alt="<?php echo $site_title; ?>" title="<?php echo $site_title; ?>">
              </a>
              <?php echo $this->partial('common/search-form'); ?>
              <div class="align-self-end align-self-center">
                <?php echo $this->partial(
                    'main-navigation.phtml',
                    ['menu' => $site->publicNav()->menu()]
                ); ?>
              </div>
              <?php if ($org_logo): ?>
                <a class="navbar-brand border-start ps-3 align-self-end align-self-center" href="<?php echo $this->themeSetting('org_url', 'https://omeka.org/s/'); ?>" target="_blank">
                  <img class="" src="<?php echo $org_logo; ?>" alt="<?php echo $org_title; ?>" title="<?php echo $org_title; ?>">
                </a>
              <?php endif; ?>
          </div>
        </nav>

        <div class="container mt-5" id="content" role="main">
            <?php echo $this->messages(); ?>
            <?php echo $this->content; ?>
        </div>
        <footer class="container">
            <span class="powered-by"><?php echo $translate('Powered by Omeka S'); ?></span>
        </footer>
    </body>
</html>
