<?php 

// create iterator
$iterator = new RecursiveIteratorIterator(
    $menu->getContainer(),
    RecursiveIteratorIterator::SELF_FIRST
);

?>
<button class="navbar-toggler m-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarNav">
  <ul class="navbar-nav ">
    <?php foreach ($iterator as $page): ?>
      <li class="nav-item">
        <?php $page->setClass('nav-link'); echo $menu->htmlify($page, NULL, FALSE) ?>
      </li>
    <?php endforeach; ?>
  </ul>
</div>